"""Connections that are not in any catalogue, added on every update.

Kept as QGIS connection XML lines (as written by Settings > Options >
Export connections) so new ones can be pasted in. EVY lines go through the
Edenvale Young Niagara proxy (Ordnance Survey APIs with the company key) and
only work on the EVY VPN; they are added only when "EVY staff" is ticked.

OS Vector Tile API connections use OS's "Open" style sheets (for the OpenData tiles the
proxy serves, overzoom allowed; tiles go up to zoom 15). The Premium-only styles (3D, ESRI,
No Labels) do not render with them and are left out.
"""

PUBLIC = """
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/7bacc94a-3a37-4918-a43b-977678bff8f5?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Ash tree distribution in Great Britain 2007 View Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/8707816a-0fe4-40f0-96ba-7ec0136d1c73?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Countryside Survey Environmental Zones View Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/b1540d75-bbec-4181-902f-f0b43eeee359?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Environmental Change Network (ECN) monitoring sites view service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/dddc328b-6010-4d4f-8ef4-af1b14d93d3c?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Estimates of linear feature lengths in Great Britain [Countryside Survey] web map service (WMS)" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/cca47088-8cdd-4d7a-86b4-90f0a1766364?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Integrated Hydrological Units of the United Kingdom View Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/235c42f5-6281-40f6-a74c-1b4eb29c78b1?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: ITE land classification of Great Britain web map service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/ebde9ef5-744e-4813-ac2f-864dfe14868b?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Classification of Shetland 1974 web map service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/18cd1739-fa2c-414b-b7e2-887771fffaa6?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2007 (1km dominant target class, N. Ireland) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/5d324260-22d9-11e4-8c21-0800200c9a66?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2007 (1km percentage aggregate class, GB) Web Map Service v1.2" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/de3068d1-6c80-400d-b1d8-af0f57449d21?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2007 (1km percentage aggregate class, N. Ireland) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/d1775d53-f51f-4d87-a774-41c992750d90?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2007 (1km percentage target class, N. Ireland) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/54dc0330-22d9-11e4-8c21-0800200c9a66?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2007 v1.2 (1km dominant aggregate class, GB) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/b4fb2b30-22d7-11e4-8c21-0800200c9a66?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2007 v1.2 (1km dominant aggregate class, N. Ireland) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/5914cae0-22d9-11e4-8c21-0800200c9a66?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2007 v1.2 (1km dominant target class, GB) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/ca28b6b5-eeb8-4861-af6d-e22e36ff2314?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2015 (1km dominant aggregate class) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/184a89d2-04d1-4955-9b45-5e90a862acda?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2015 (1km dominant target class) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/05e01504-0505-4846-92e3-991b8c95ad20?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2015 (1km percentage aggregate class, GB) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/34e168c2-0666-4481-a338-271d672645eb?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2015 (1km percentage aggregate class, N. Ireland) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/2b2f193e-907b-4cc8-8b65-82eff6aed2d0?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2015 (1km percentage target class, GB) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/aa2b1344-1644-4e9a-8bec-a852be9ac30e?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2015 (1km percentage target class, N. Ireland) Web Map Service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/78b670a2-5483-45ab-b54f-9dce9c378197?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2015 25m raster web service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/a687a1a1-cfbd-43f5-996f-05cee856ff2d?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2017 25m raster web service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/032da3fa-10ba-42cc-b719-b19b6dfd11f5?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2018 25m raster web service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/4f88a4f0-3bbc-4735-b078-11919d1865e0?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2019 25m raster web service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/51bcb92a-dd88-4034-ba65-a9d432dd632a?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2020 10m web map service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/315e9cbb-efdc-4726-bf97-bd9176af3c9d?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2020 25m web map service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/2ad19a50-b940-469e-a40d-17818b77020c?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2021 10m web map service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/68712ac3-d740-41df-bcb3-4d341f859909?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Land Cover Map 2023 10m web map service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/c89cc9a0-dcfa-11e3-8b68-0800200c9a66?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: LiDAR based Digital Surface Model (DSM) for South West England Web Map Service (WMS)" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/968b7ab9-2ee8-4b5c-bdfb-ad42745b04dc?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: LiDAR based Digital Terrain Model (DTM) for South West England Web Map Service (WMS)" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/0c5c5e20-246e-11e4-8c21-0800200c9a66?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Soil, vegetation and geology maps of the Moor House National Nature Reserve WMS" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/a78c90a2-8da4-4f0a-9c6a-c1d1a4a3c2b0?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: UKCEH digital river network of Great Britain web map service" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/2be6d1c5-7b82-4d83-9291-defa59aa8aae?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Web map service for bee nectar plant diversity of Great Britain" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/090f990e-e24c-499b-87eb-33a193b50c63?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Web map service for Model estimates of expected diversity of positive plant habitat condition indicators" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/6372b558-ba64-4fbe-8766-019e01535b37?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Web Map Service for model estimates of topsoil properties [Countryside Survey]" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/47414349-b05f-4965-81d6-165392b549d8?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Web Map Service for topsoil properties from the Countryside Survey of Great Britain, 2007 using a generalized additive model" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/da198f95-d93d-4759-bf51-6ec0b8bdfaee?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: Web Map Service of Climate suitability for Phytophthora ramorum and Phytophthora kernoviae infection in the UK" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/ab7216df-6a37-468a-be41-2362bd487639?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: WMS for sulphur and nitrogen atmospheric Concentration Based Estimated Deposition (CBED), 2011-2013" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/fe7886dc-1953-40f1-acf7-2fc32ebe1105?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: WMS for sulphur and nitrogen atmospheric Concentration Based Estimated Deposition (CBED), 2013-2015" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/ebb12432-54ee-474d-a839-48d1174a4a65?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: WMS for sulphur and nitrogen atmospheric Concentration Based Estimated Deposition (CBED), 2017-2019" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/f7431ee8-9508-4059-ad8b-900ad3c20e17?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: WMS of spatial masks for calcareous, coastal, upland and lowland heath landscapes in England" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://catalogue.ceh.ac.uk/maps/e4b36270-8246-4afa-8eff-6781210a0477?cache=false" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS CEH: WMS of wooded riparian zones in Great Britain" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/BGS_Detailed_Geology/MapServer/WMSServer?" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: BGS Geology 50K WMS" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://ogc.bgs.ac.uk/cgi-bin/BGS_Bedrock_and_Superficial_Geology/ows?" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: BGS Geology 625K and 1:1 million offshore sediments WMS" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/UKSO/UKSO_BGS/MapServer/WMSServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: Soil property data" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/Offshore/Products_WMS/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: Offshore marine WMS" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="http://map.bgs.ac.uk/arcgis/services/UKSO/UKSO_BGS_NSI/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: Advanced soil geochemical atlas" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="http://map.bgs.ac.uk/arcgis/services/BCCS/BCCS_WMS/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: Normal background concentrations of contaminants WMS" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/geophysics_midlands_hires/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: HiRes1 airborne geophysical data WMS" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/radon/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: Indicative atlas of radon in Great Britain" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GSHP/GSHP_WMS/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: Open-loop ground source heat pump viability screening map" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/UKSO/UKSO_BGS_TellusSW/MapServer/WMSServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: TellusSW airborne geophysical data WMS" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="http://ogc.bgs.ac.uk/cgi-bin/BGS_1GE_Geology/wms?" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WMS BGS: Sample 1:50 000-scale natural ground stability data WMS" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/boreholes/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Boreholes" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/AGS/AGS_Export/MapServer/WMSServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: AGS Boreholes" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/collections/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Collections" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/hazards/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Hazards" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/geochemistry/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Geochemistry" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/geophysics/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Geophysics" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/products/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Map products" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/hydrogeology/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Hydrogeology" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Offshore/offshore_data/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Offshore" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/minerals_wms/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Mineral resources" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Offshore/21CXRM/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: 21st Century Roadmap Palaeozoic" dpiMode="7"/>
    <wms ignoreGetMapURI="0" invertAxisOrientation="0" username="" ignoreGetFeatureInfoURI="0" url="https://map.bgs.ac.uk/arcgis/services/GeoIndex_Offshore/offshore_cultural/MapServer/WmsServer" smoothPixmapTransform="0" ignoreAxisOrientation="0" password="" name="WFS WMS: Offshore (cultural data)" dpiMode="7"/>
    <wfs ignoreAxisOrientation="0" username="" maxnumfeatures="100" version="auto" password="" url="http://ogc2.bgs.ac.uk/cgi-bin/UKWM/ows?service=WFS&request=GetCapabilities&" pagingenabled="enabled" pagesize="100" name="WFS BGS: World Mineral Statistics dataset" invertAxisOrientation="0"/>
    <wfs ignoreAxisOrientation="0" username="" maxnumfeatures="100" version="auto" password="" url="http://ogc.bgs.ac.uk/digmap625k_gsml_insp_gs/wfs?service=WFS&request=GetCapabilities&AcceptVersions=2.0.0&" pagingenabled="enabled" pagesize="100" name="WFS BGS: UK onshore bedrock geological data WFS services (1:625 000 scale) INSPIRE" invertAxisOrientation="0"/>
    <wfs ignoreAxisOrientation="0" username="" maxnumfeatures="100" version="auto" password="" url="http://ogc.bgs.ac.uk/digmap625k_gsml_cgi_gs/wfs?service=WFS&request=GetCapabilities&AcceptVersions=2.0.0&" pagingenabled="enabled" pagesize="100" name="WFS BGS: UK onshore bedrock geological data WFS services (1:625 000 scale) CGI" invertAxisOrientation="0"/>
    <xyztiles referer="" username="" http-header:referer="" zmax="15" password="" url="https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png" zmin="0" authcfg="" name="XYZ MZ: Mapzen Global Terrain" tilePixelRatio="0"/>
    <xyztiles referer="" username="" http-header:referer="" zmax="19" password="" url="https://tile.openstreetmap.org/{z}/{x}/{y}.png" zmin="0" authcfg="" name="XYZ OSM: OpenStreetMap" tilePixelRatio="0"/>
"""

EVY = """
    <wms ignoreGetMapURI="0" ignoreAxisOrientation="0" username="" dpiMode="7" ignoreGetFeatureInfoURI="0" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/raster/v1/wmts" name="WMTS OS: OS Maps API" smoothPixmapTransform="0" invertAxisOrientation="0"/>
    <xyztiles referer="" username="" http-header:referer="" zmax="20" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/raster/v1/zxy/Light_3857/{z}/{x}/{y}.png" zmin="7" authcfg="" name="XYZ OS: OS Maps API Light 3857" tilePixelRatio="0"/>
    <xyztiles referer="" username="" http-header:referer="" zmax="20" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/raster/v1/zxy/Outdoor_3857/{z}/{x}/{y}.png" zmin="7" authcfg="" name="XYZ OS: OS Maps API Outdoor 3857" tilePixelRatio="0"/>
    <xyztiles referer="" username="" http-header:referer="" zmax="20" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/raster/v1/zxy/Road_3857/{z}/{x}/{y}.png" zmin="7" authcfg="" name="XYZ OS: OS Maps API Road 3857" tilePixelRatio="0"/>
    <vectortile referer="" username="" http-header:referer="" zmax="19" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/ngd/ota/v1/collections/ngd-base/tiles/3857/{z}/{y}/{x}" zmin="6" styleUrl="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/ngd/ota/v1/collections/ngd-base/styles/3857" authcfg="" serviceType="" name="VT OS: OS NGD Tile API Outdoor"/>
    <vectortile referer="" username="" http-header:referer="" zmax="19" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/ngd/ota/v1/collections/ngd-base/tiles/3857/{z}/{y}/{x}" zmin="6" styleUrl="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/ngd/ota/v1/collections/ngd-base/styles/blackwhite-3857" authcfg="" serviceType="" name="VT OS: OS NGD Tile API Black and White"/>
    <vectortile referer="" username="" http-header:referer="" zmax="19" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/ngd/ota/v1/collections/ngd-base/tiles/3857/{z}/{y}/{x}" zmin="6" styleUrl="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/ngd/ota/v1/collections/ngd-base/styles/light-3857" authcfg="" serviceType="" name="VT OS: OS NGD Tile API Light"/>
    <vectortile referer="" username="" http-header:referer="" zmax="19" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/ngd/ota/v1/collections/ngd-base/tiles/3857/{z}/{y}/{x}" zmin="6" styleUrl="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/ngd/ota/v1/collections/ngd-base/styles/road-3857" authcfg="" serviceType="" name="VT OS: OS NGD Tile API Road"/>
    <vectortile referer="" username="" http-header:referer="" zmax="15" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/v1/vts/tile/{z}/{y}/{x}.pbf?srs=3857" zmin="6" styleUrl="https://raw.githubusercontent.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/master/OS_VTS_3857_Open_Black_and_White.json" authcfg="" serviceType="" name="VT OS: OS Vector Tile API Black and White"/>
    <vectortile referer="" username="" http-header:referer="" zmax="15" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/v1/vts/tile/{z}/{y}/{x}.pbf?srs=3857" zmin="6" styleUrl="https://raw.githubusercontent.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/master/OS_VTS_3857_Open_Dark.json" authcfg="" serviceType="" name="VT OS: OS Vector Tile API Dark"/>
    <vectortile referer="" username="" http-header:referer="" zmax="15" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/v1/vts/tile/{z}/{y}/{x}.pbf?srs=3857" zmin="6" styleUrl="https://raw.githubusercontent.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/master/OS_VTS_3857_Open_Greyscale.json" authcfg="" serviceType="" name="VT OS: OS Vector Tile API Greyscale"/>
    <vectortile referer="" username="" http-header:referer="" zmax="15" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/v1/vts/tile/{z}/{y}/{x}.pbf?srs=3857" zmin="6" styleUrl="https://raw.githubusercontent.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/master/OS_VTS_3857_Open_Light.json" authcfg="" serviceType="" name="VT OS: OS Vector Tile API Light"/>
    <vectortile referer="" username="" http-header:referer="" zmax="15" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/v1/vts/tile/{z}/{y}/{x}.pbf?srs=3857" zmin="6" styleUrl="https://raw.githubusercontent.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/master/OS_VTS_3857_Open_Outdoor.json" authcfg="" serviceType="" name="VT OS: OS Vector Tile API Outdoor"/>
    <vectortile referer="" username="" http-header:referer="" zmax="15" password="" url="https://mapcache.niagara.ad.edenvaleyoung.com/maps/vector/v1/vts/tile/{z}/{y}/{x}.pbf?srs=3857" zmin="6" styleUrl="https://raw.githubusercontent.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/master/OS_VTS_3857_Open_Road.json" authcfg="" serviceType="" name="VT OS: OS Vector Tile API Road"/>
"""
